//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CTRE_NETMF_NATIVE_H_
#define _CTRE_NETMF_NATIVE_H_

#include <TinyCLR_Interop.h>
struct Library_ctre_netmf_native_CTRE_Native_CAN
{
    TINYCLR_NATIVE_DECLARE(Send___STATIC__I4__U4__U8__U4__U4);
    TINYCLR_NATIVE_DECLARE(Receive___STATIC__I4__U4__BYREF_U8__BYREF_U4);
    TINYCLR_NATIVE_DECLARE(GetSendBuffer___STATIC__I4__U4__BYREF_U8);
    TINYCLR_NATIVE_DECLARE(OpenStream___STATIC__I4__BYREF_U4__U4__U4);
    TINYCLR_NATIVE_DECLARE(GetStreamSize___STATIC__I4__U4__BYREF_U4);
    TINYCLR_NATIVE_DECLARE(ReadStream___STATIC__I4__U4__BYREF_U4__BYREF_U8__BYREF_U4__BYREF_U4);
    TINYCLR_NATIVE_DECLARE(CloseStream___STATIC__VOID__U4);

    //--//

};

struct Library_ctre_netmf_native_CTRE_Native_HDU
{
    TINYCLR_NATIVE_DECLARE(GetJoy___STATIC__I4__BYREF_I4__SZARRAY_I4__U4__SZARRAY_R4__U4);
    TINYCLR_NATIVE_DECLARE(SetMode___STATIC__VOID__U4);
    TINYCLR_NATIVE_DECLARE(GetMode___STATIC__U4);

    //--//

};

struct Library_ctre_netmf_native_CTRE_Native_Misc
{
    TINYCLR_NATIVE_DECLARE(TimeToProcess___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(Bitmap_ConvertBPP___STATIC__I4__SZARRAY_U1__SZARRAY_U1__U4);
    TINYCLR_NATIVE_DECLARE(GetBitmap___STATIC__SZARRAY_U1__SZARRAY_U1__OBJECT__U4);

    //--//

};

struct Library_ctre_netmf_native_CTRE_Native_System
{
    TINYCLR_NATIVE_DECLARE(IoControl___STATIC__I4__U4__U8__SZARRAY_U1__SZARRAY_U1);

    //--//

};

struct Library_ctre_netmf_native_CTRE_Native_Watchdog
{
    TINYCLR_NATIVE_DECLARE(Feed___STATIC__I4__U4);
    TINYCLR_NATIVE_DECLARE(GetEnableBits___STATIC__I4__BYREF_U4);
    TINYCLR_NATIVE_DECLARE(RegisterSafeOutput___STATIC__I4__U4);
    TINYCLR_NATIVE_DECLARE(RegisterSafePWMOutput___STATIC__I4__U4);

    //--//

};

struct Library_ctre_netmf_native_CTRE_Native_CAN__CanSessionMsg
{
    static const int FIELD__arbId = 1;
    static const int FIELD__len = 2;
    static const int FIELD__D0D1D2D3 = 3;
    static const int FIELD__D4D5D6D7 = 4;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ctre_netmf_native;

#endif  //_CTRE_NETMF_NATIVE_H_
