//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "ctre_netmf_native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_ctre_netmf_native_CTRE_Native_CAN::Send___STATIC__I4__U4__U8__U4__U4,
    Library_ctre_netmf_native_CTRE_Native_CAN::Receive___STATIC__I4__U4__BYREF_U8__BYREF_U4,
    Library_ctre_netmf_native_CTRE_Native_CAN::GetSendBuffer___STATIC__I4__U4__BYREF_U8,
    Library_ctre_netmf_native_CTRE_Native_CAN::OpenStream___STATIC__I4__BYREF_U4__U4__U4,
    Library_ctre_netmf_native_CTRE_Native_CAN::GetStreamSize___STATIC__I4__U4__BYREF_U4,
    Library_ctre_netmf_native_CTRE_Native_CAN::ReadStream___STATIC__I4__U4__BYREF_U4__BYREF_U8__BYREF_U4__BYREF_U4,
    Library_ctre_netmf_native_CTRE_Native_CAN::CloseStream___STATIC__VOID__U4,
    Library_ctre_netmf_native_CTRE_Native_HDU::GetJoy___STATIC__I4__BYREF_I4__SZARRAY_I4__U4__SZARRAY_R4__U4,
    Library_ctre_netmf_native_CTRE_Native_HDU::SetMode___STATIC__VOID__U4,
    Library_ctre_netmf_native_CTRE_Native_HDU::GetMode___STATIC__U4,
    Library_ctre_netmf_native_CTRE_Native_Misc::TimeToProcess___STATIC__I4,
    Library_ctre_netmf_native_CTRE_Native_Misc::Bitmap_ConvertBPP___STATIC__I4__SZARRAY_U1__SZARRAY_U1__U4,
    Library_ctre_netmf_native_CTRE_Native_Misc::GetBitmap___STATIC__SZARRAY_U1__SZARRAY_U1__OBJECT__U4,
    Library_ctre_netmf_native_CTRE_Native_System::IoControl___STATIC__I4__U4__U8__SZARRAY_U1__SZARRAY_U1,
    Library_ctre_netmf_native_CTRE_Native_Watchdog::Feed___STATIC__I4__U4,
    Library_ctre_netmf_native_CTRE_Native_Watchdog::GetEnableBits___STATIC__I4__BYREF_U4,
    Library_ctre_netmf_native_CTRE_Native_Watchdog::RegisterSafeOutput___STATIC__I4__U4,
    Library_ctre_netmf_native_CTRE_Native_Watchdog::RegisterSafePWMOutput___STATIC__I4__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ctre_netmf_native =
{
    "ctre_netmf_native", 
    0x138850F8,
    method_lookup
};

